import 'package:flangapp_app/enum/action_type.dart';
import 'package:flangapp_app/models/navigation_item.dart';

import '../enum/background_mode.dart';
import '../enum/load_indicator.dart';
import '../enum/template.dart';

class Config {

  /// Generated by SiteNative 16-08-2022 12:07:04
  /// App UID: 4a0577fb-6d40-e59f-e09b-ef43602e1fe1
  /// Version: https://apps.mbh-fiduciaire.site/backend/
  /// API server: {VERSION}

  /// *** App config *** ///
  // App name
  static String appName = "TECHNOLOGY RBS";
  // App link
  static String appLink = "https://erp.bensassiridha.com/login";
  // Display page name without app name (after 1 page)
  static bool displayTitle = true;
  // Main color (any HEX color)
  static String color = "#4CAF50";
  // Active color (any HEX color)
  static String activeColor = "#4CAF50";
  // Icon color color (any HEX color)
  static String iconColor = "#4CAF50";
  // Title color (true - white, false - black)
  static bool isDark = true;
  // Pull to refresh enabled
  static bool pullToRefresh = true;
  // User agent
  static String userAgent = "";
  // Admin email
  static String appEmail = "bensassiridha1@gmail.com";
  // Template
  static Template appTemplate = Template.drawer;
  // Loading indicator style
  static LoadIndicator indicator = LoadIndicator.line;
  // Loading indicator color
  static String indicatorColor = "#4CAF50";

  /// *** Access ** ///
  // Access to camera
  static bool accessCamera = false;
  // Access to microphone
  static bool accessMicrophone = false;
  // Access to geolocation
  static bool accessLocation = false;

  /// *** Drawer settings *** ///
  // Title
  static String drawerTitle = "";
  // Subtitle
  static String drawerSubtitle = "";
  // Background mode
  static BackgroundMode drawerBackgroundMode = BackgroundMode.color;
  // Background color (any HEX color)
  static String drawerBackgroundColor = "#4CAF50";
  // Title color (true - white, false - black)
  static bool drawerIsDark = true;
  // Background image name
  static String drawerBackgroundImage = "drawer_background.png";
  // Logo image name
  static String drawerLogoImage = "logo.png";
  // Display logo
  static bool drawerIsDisplayLogo = false;

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#4CAF50";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** PUSH OneSignal settings *** ///
  // App ID
  static String osAppID = "";
  // Signing
  static String osSigning = "ee4565f573159e4d86df03f805027cd99dda28dcc8b45262fe34611e249e8b17";
  // Enabled android?
  static bool osAndroidEnabled = false;

  /// *** Website styles *** ///
  // List div for hide in app
  static List<String> cssHideBlock = [];

  /// *** Localization *** ///
  // Name offline image
  static String offlineImage = "wifi.png";
  // Error internet connection (offline)
  static String messageErrorOffline = "No internet connection";
  // Error open web page
  static String messageErrorBrowser = "Failed to load the page. Please try again later!";
  // Name error page image
  static String errorBrowserImage = "error.png";
  // Title about exit from app (Android)
  static String titleExit = "Confirmation";
  // Message about exit from app (Android)
  static String messageExit = "Are you sure you want to exit the app?";
  // Confirm button about
  static String actionYesDownload = "Yes";
  // Cancel button
  static String actionNoDownload = "No";
  // Contact us email (About screen)
  static String contactBtn = "Contact us with email";
  // Back
  static String backBtn = "Go back";

  /// *** Navigation *** ///
  // Main app navigation
  static List<NavigationItem> mainNavigation = [
    	NavigationItem(name: "Recettes",icon: "cash-outline.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/revenue",),
	NavigationItem(name: "Dépenses",icon: "cart-outline.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/payment",),
	NavigationItem(name: "Crédit Clients",icon: "archive-outline.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/credit-note",),
	NavigationItem(name: "Débit ",icon: "remove-circle-outline.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/debit-note",),
	NavigationItem(name: "Clients",icon: "accessibility.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/customer",),
	NavigationItem(name: "Dashboard",icon: "bar-chart-outline.svg",type: ActionType.internal,value: "https://erp.bensassiridha.com/account-dashboard",),

  ];
  // Bar app navigation
  static List<NavigationItem> barNavigation = [
    
  ];
  // Modal navigation
  static List<NavigationItem> modalNavigation = [
    
  ];
}